# Site settings
title: sharils' 2¢
email: sharils@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Calico cat
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sharils.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  sharils

# Build settings
markdown: kramdown
